#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# TradeBuddy — install.sh
# One-command local installer for macOS (and Linux).
#
# Can be run as a single curl command on a brand new machine:
#   curl -fsSL https://raw.githubusercontent.com/timwangnz/stock-trading-app/main/install.sh | bash
#
# What it does:
#   1. Downloads docker-compose.yml and backup.sh if not already present
#   2. Checks Docker is installed and running
#   3. Asks for your API keys interactively
#   4. Generates all secrets automatically
#   5. Writes .env
#   6. Pulls and starts the app with docker compose
#   7. Schedules a daily midnight backup to ~/Documents/TradeBuddy-Backups/
#   8. Opens http://localhost:3001 in your browser
# ─────────────────────────────────────────────────────────────────

set -e

REPO_RAW="https://raw.githubusercontent.com/timwangnz/stock-trading-app/main"

# ── Download companion files if not already present ───────────────
for FILE in docker-compose.yml backup.sh; do
  if [ ! -f "$FILE" ]; then
    echo "Downloading $FILE…"
    curl -fsSL "$REPO_RAW/$FILE" -o "$FILE"
  fi
done
chmod +x backup.sh

# ── Colours ───────────────────────────────────────────────────────
BOLD="\033[1m"
BLUE="\033[1;34m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
RED="\033[1;31m"
DIM="\033[2m"
RESET="\033[0m"

# ── Helpers ───────────────────────────────────────────────────────
print_header() {
  echo ""
  echo -e "${BLUE}${BOLD}$1${RESET}"
  echo -e "${DIM}$(printf '─%.0s' {1..50})${RESET}"
}

print_step() {
  echo -e "${GREEN}✓${RESET} $1"
}

print_info() {
  echo -e "${DIM}  $1${RESET}"
}

print_warn() {
  echo -e "${YELLOW}⚠${RESET}  $1"
}

print_error() {
  echo -e "${RED}✗${RESET} $1"
}

ask() {
  local prompt="$1"
  local var="$2"
  local default="$3"
  local secret="$4"

  if [ -n "$default" ]; then
    echo -ne "${BOLD}$prompt${RESET} ${DIM}[${default}]${RESET}: "
  else
    echo -ne "${BOLD}$prompt${RESET}: "
  fi

  if [ "$secret" = "true" ]; then
    read -rs value
    echo ""
  else
    read -r value
  fi

  if [ -z "$value" ] && [ -n "$default" ]; then
    value="$default"
  fi

  eval "$var='$value'"
}

gen_secret() {
  node -e "console.log(require('crypto').randomBytes(32).toString('hex'))" 2>/dev/null \
    || openssl rand -hex 32
}

# ── Banner ────────────────────────────────────────────────────────
clear
echo ""
echo -e "${BLUE}${BOLD}"
echo "  ████████╗██████╗  █████╗ ██████╗ ███████╗"
echo "     ██╔══╝██╔══██╗██╔══██╗██╔══██╗██╔════╝"
echo "     ██║   ██████╔╝███████║██║  ██║█████╗  "
echo "     ██║   ██╔══██╗██╔══██║██║  ██║██╔══╝  "
echo "     ██║   ██║  ██║██║  ██║██████╔╝███████╗"
echo "     ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝"
echo -e "${RESET}"
echo -e "  ${BOLD}Buddy${RESET} — Vibe Trading Platform"
echo -e "  ${DIM}Local installer · takes about 2 minutes${RESET}"
echo ""

# ── Step 1: Check Docker ──────────────────────────────────────────
print_header "Step 1 — Checking Docker"

if ! command -v docker &>/dev/null; then
  print_error "Docker is not installed."
  echo ""
  echo "  Please install Docker Desktop first:"
  echo -e "  ${BLUE}https://www.docker.com/products/docker-desktop/${RESET}"
  echo ""
  echo "  Then run this script again."
  exit 1
fi

if ! docker info &>/dev/null; then
  print_error "Docker is installed but not running."
  echo ""
  echo "  Please start Docker Desktop and try again."
  exit 1
fi

print_step "Docker is running ($(docker --version | cut -d' ' -f3 | tr -d ','))"

# ── Check for existing .env ───────────────────────────────────────
if [ -f .env ]; then
  echo ""
  print_warn ".env already exists."
  ask "  Overwrite it with fresh settings? (y/N)" OVERWRITE_ENV "N"
  if [[ ! "$OVERWRITE_ENV" =~ ^[Yy]$ ]]; then
    echo ""
    print_step "Keeping existing .env — skipping to build step."
    SKIP_ENV=true
  fi
fi

# ── Step 2: Admin account ─────────────────────────────────────────
if [ "${SKIP_ENV}" != "true" ]; then

print_header "Step 2 — Admin account"

echo -e "  Create your admin account. You will use this to sign in and"
echo -e "  configure API keys (Polygon, Google, Resend) inside the app."
echo -e "  ${DIM}Credentials are stored locally in .env — never sent anywhere.${RESET}"
echo ""

ask "  Admin name" ADMIN_NAME "Admin"
ask "  Admin email" ADMIN_EMAIL ""
ask "  Admin password (min 8 characters)" ADMIN_PASSWORD "" "true"
echo ""

# ── Step 3: Generate secrets ─────────────────────────────────────
print_header "Step 3 — Generating secrets"

DB_PASSWORD=$(gen_secret)
JWT_SECRET=$(gen_secret)
SNAPSHOT_SECRET=$(gen_secret)
LLM_ENCRYPTION_KEY=$(gen_secret)

print_step "DB password generated"
print_step "JWT secret generated"
print_step "Snapshot secret generated"
print_step "LLM encryption key generated"

# ── Write .env ────────────────────────────────────────────────────

cat > .env <<EOF
# ── Generated by install.sh on $(date) ──

# Database (managed by Docker — do not change DB_HOST)
DB_HOST=db
DB_PORT=5432
DB_USER=tradebuddy
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=tradebuddy

# App
API_PORT=3001
APP_URL=http://localhost:3001
NODE_ENV=production

# Secrets (auto-generated — do not share)
JWT_SECRET=${JWT_SECRET}
SNAPSHOT_SECRET=${SNAPSHOT_SECRET}
LLM_ENCRYPTION_KEY=${LLM_ENCRYPTION_KEY}

# Admin setup — removed automatically after first boot
SETUP_ADMIN_NAME=${ADMIN_NAME}
SETUP_ADMIN_EMAIL=${ADMIN_EMAIL}
SETUP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

print_step ".env written"

fi # end SKIP_ENV

# ── Step 4: Build & start ─────────────────────────────────────────
print_header "Step 4 — Building & starting TradeBuddy"

echo -e "  ${DIM}This takes 2–3 minutes on first run (downloading and building).${RESET}"
echo -e "  ${DIM}Subsequent starts take about 5 seconds.${RESET}"
echo ""

docker compose pull
docker compose up -d

# Wait for the app to be ready
echo ""
echo -ne "  Waiting for app to be ready"
for i in $(seq 1 30); do
  if curl -sf http://localhost:3001/api/health &>/dev/null; then
    break
  fi
  echo -ne "."
  sleep 2
done
echo ""

if ! curl -sf http://localhost:3001/api/health &>/dev/null; then
  print_warn "App is taking longer than expected to start."
  print_info "Check logs with: docker compose logs -f app"
else
  print_step "App is ready!"

  # Scrub admin credentials from .env now that the container has used them
  sed -i.bak '/^SETUP_ADMIN_/d' .env && rm -f .env.bak
  print_step "Admin credentials removed from .env (stored securely in the database)"
fi

# ── Step 5: Set up daily backup ───────────────────────────────────
print_header "Step 5 — Setting up daily backup"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_SCRIPT="$SCRIPT_DIR/backup.sh"
BACKUP_DIR="$HOME/Documents/TradeBuddy-Backups"

# Make backup.sh executable
chmod +x "$BACKUP_SCRIPT"
print_step "backup.sh is ready"

# Create backup directory now so iCloud starts syncing it immediately
mkdir -p "$BACKUP_DIR"
print_step "Backup folder created: $BACKUP_DIR"

# Install cron job (runs backup.sh at midnight daily)
CRON_JOB="0 0 * * * cd \"$SCRIPT_DIR\" && bash \"$BACKUP_SCRIPT\" >> \"$BACKUP_DIR/backup.log\" 2>&1"

# Check if it's already scheduled
if crontab -l 2>/dev/null | grep -qF "$BACKUP_SCRIPT"; then
  print_step "Daily backup already scheduled — skipping"
else
  # Add to crontab
  ( crontab -l 2>/dev/null; echo "$CRON_JOB" ) | crontab -
  print_step "Daily backup scheduled at midnight (cron)"
fi

print_info "Backups saved to: $BACKUP_DIR"
print_info "iCloud will sync this folder automatically if enabled"
print_info "Last 7 days of backups are kept; older ones are deleted"
print_info "Run manually anytime: bash backup.sh"

# ── Done ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}${BOLD}  🎉 TradeBuddy is running!${RESET}"
echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "  Open your browser:  ${BLUE}${BOLD}http://localhost:3001${RESET}"
echo ""
echo -e "  Sign in as admin, then go to ${BOLD}My Keys → App Settings${RESET} to add:"
echo -e "  ${DIM}  • Polygon API key  — live market data (polygon.io)${RESET}"
echo -e "  ${DIM}  • Google Client ID — Google sign-in (optional)${RESET}"
echo -e "  ${DIM}  • Resend API key   — email delivery (optional)${RESET}"
echo ""
echo -e "  ${DIM}Useful commands:${RESET}"
echo -e "  ${DIM}  docker compose stop        ← stop TradeBuddy${RESET}"
echo -e "  ${DIM}  docker compose start       ← start again${RESET}"
echo -e "  ${DIM}  docker compose logs -f app ← view logs${RESET}"
echo -e "  ${DIM}  bash backup.sh             ← run backup now${RESET}"
echo ""

# Open browser (macOS)
if command -v open &>/dev/null; then
  sleep 1
  open http://localhost:3001
fi
